port: 443
log_level: 1
plugins:
    # NOTE: run bundle after changing plugin configurations to update required gems

    - name: 'Example'
      path: './plugins/siriproxy-example'

    # - name: 'Thermostat'
    #   git: 'git://github.com/plamoni/SiriProxy-Thermostat.git'
    #   host: '192.168.2.71' 

    # - name: 'Twitter'
    #   path: './plugins/siriproxy-twitter' # path works just like specifing in gemfile 
    #   consumer_key: "YOUR_KEY" 
    #   consumer_secret: "YOUR_SECRET"
    #   oauth_token: "YOUR_TOKEN" 
    #   oauth_token_secret: "YOUR_TOKEN_SECRET"

    # Note: Eliza should not be run with other plugins
    # - name: 'Eliza'
    #   path: './plugins/siriproxy-eliza' # path works just like specifing in gemfile 

    # Below are not actual plugins, just further example of config options

    # - SimplePlugin # simple syntax for plugins that are in rubygems and have no config 

    # - name: 'AnotherPlugin'
    #   git: 'git://github.com/netpro2k/SiriProxy-AnotherPlugin.git' # git works just like specifying in Gemfile


#

pluginManager: 
  - name: "honey" #primary  
    - class: "honey" #class name -- will resutl in a require "siriproxypm-#{$APP_CONFIG.PluginManager.class.downcase}"  
      #class  defined here should be SiriProxy::SiriProxyManager::#{$APP_CONFIG.PluginManager.class}

      
speakers:
  "alice":
    identify: "this is alice"
    welcome: "Hi alice!"
    plugins: [ Example, Ping ]
    expires: 600 #default expiration for this speaker activity is 10 minutes, instead of 5


  "bob":
    identify: [/this is bob(by)?/i ]
    welcome: "Hey there bob"
    plugins: [ Example, Alarms, Music ] #this is lke a menu script to follow.
  

client_preferences:
  "192.168.1.2":
    - speaker: "alice"

  "192.168.1.143":
    - speaker: "bob"


