port: 443
log_level: 1
plugins:
    # NOTE: run bundle after changing plugin configurations to update required gems

    - name: 'Example'
      path: './plugins/siriproxy-example'

    - name: 'Numbers'
      path: './plugins/siriproxy-numbers'

    - name: 'Hello'
      path: './plugins/siriproxy-hello'

    # - name: 'Thermostat'
    #   git: 'git://github.com/plamoni/SiriProxy-Thermostat.git'
    #   host: '192.168.2.71' 

    # - name: 'Twitter'
    #   path: './plugins/siriproxy-twitter' # path works just like specifing in gemfile 
    #   consumer_key: "YOUR_KEY" 
    #   consumer_secret: "YOUR_SECRET"
    #   oauth_token: "YOUR_TOKEN" 
    #   oauth_token_secret: "YOUR_TOKEN_SECRET"

    # Note: Eliza should not be run with other plugins
    # - name: 'Eliza'
    #   path: './plugins/siriproxy-eliza' # path works just like specifing in gemfile 

    # Below are not actual plugins, just further example of config options

    # - SimplePlugin # simple syntax for plugins that are in rubygems and have no config 

    # - name: 'AnotherPlugin'
    #   git: 'git://github.com/netpro2k/SiriProxy-AnotherPlugin.git' # git works just like specifying in Gemfile


#

pluginManager: 
  class: 
     name: "Honey" 
     path: './managers/siriproxypm-honey'
  #the identifier used to take control of system primary.  the plugin manager enforces that all text commands to be processed should start with the identifier
  identifier: ["honey" ,"/(hey|hi|) honey/i" ]
  goodbye: ["goodbye" , "bye" ,"we will talk later", "see you", "ciao" ]
  open: 60 #default time to keep connection open

      
speakers:
  alice:
    identify: this is alice
    welcome: Hi alice!
    plugins: [ Example, Numbers ]
    #default expiration for this speaker activity is 10 minutes, instead of 5  

  bob:
    identify:   [ "/this is bob(by)?/i" , "/this is robert/i" ]
    welcome: Hey there Mr. Bill
    plugins: [ Example, Numbers, Hello ] 
    #this is lke a menu script to follow.
  
  guest:
    identify: /guest access/i 
    welcome: Guest Access Allowed
    plugins: [ Numbers ] 


client_preferences:
  "192.168.1.100":
    speakers: "alice"
    #only allowed speaker is alice
    
  "192.168.1.101":
    speakers: ["bob", "alice"] 
    #default speaker is bob.  Allowed to cede control to alice

  "192.168.1.50-192.168.1.99,192.168.1.102": 
     #key is dhcp range for guest connections on wifi network.  192.168.1.102 is for my mom.
     speakers: [guest,bob,alice]




