port: 443
log_level: 1
plugins:
    # NOTE: run bundle after changing plugin configurations to update required gems

    - name: 'Example'
      path: './plugins/siriproxy-example'

    # - name: 'Thermostat'
    #   git: 'git://github.com/plamoni/SiriProxy-Thermostat.git'
    #   host: '192.168.2.71' 

    # - name: 'Twitter'
    #   path: './plugins/siriproxy-twitter' # path works just like specifing in gemfile 
    #   consumer_key: "YOUR_KEY" 
    #   consumer_secret: "YOUR_SECRET"
    #   oauth_token: "YOUR_TOKEN" 
    #   oauth_token_secret: "YOUR_TOKEN_SECRET"

    # Note: Eliza should not be run with other plugins
    # - name: 'Eliza'
    #   path: './plugins/siriproxy-eliza' # path works just like specifing in gemfile 

    # Below are not actual plugins, just further example of config options

    # - SimplePlugin # simple syntax for plugins that are in rubygems and have no config 

    # - name: 'AnotherPlugin'
    #   git: 'git://github.com/netpro2k/SiriProxy-AnotherPlugin.git' # git works just like specifying in Gemfile


#

pluginManager: 
  - name: "honey" 
    #used to take control of system primary  
    - class: "honey" 
      #class name -- will resutl in a require "siriproxypm-#{$APP_CONFIG.PluginManager.class.downcase}"  
      #class  defined here should be SiriProxy::SiriProxyManager::#{$APP_CONFIG.PluginManager.class}

      
speakers:
  "alice":
    identify: "this is alice"
    welcome: "Hi alice!"
    plugins: [ "Example", "Ping" ]
    expires: 600 
    #default expiration for this speaker activity is 10 minutes, instead of 5  

  "bob":
    identify: [/this is bob(by)?/i ]
    welcome: "Hey there bob"
    plugins: [ Example, Alarms, Music ] 
    #this is lke a menu script to follow.
  
  "guest":
    identify: /guest access/i 
    welcome: "Guest Access Allowed"
    plugins: [ Speakers ] 


client_preferences:
  "192.168.1.100":
    speakers: "alice"
    #only allowed speaker is alice
    
  "192.168.1.101":
    speaker: ["bob", "alice"] 
    #default speaker is bob.  Allowed to cede control to alice

  "192.168.1.50-192.168.1.99,192.168.1.102": 
     #key is dhcp range for guest connections on wifi network.  192.168.1.102 is for my mom.
     speaker: "guest"




